//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.10 at 03:57:13 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://crud.ws.com/operations/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ws.crud.operations.types;
